### ISSUE TITLE
Create The Messages Schema and Its Associated Controllers

### ISSUE THREAD

**Issue by SirSanctified** [DevsKonnekt/DevsKonnekt#17]
This entity represents the messages that users send or receive on our platform. Determine the required attributes and relationships.

**Comment by SirSanctified** [comment]
@Marrwan you've been inactive and I have assigned this task to someone else for progress' sake

**Comment by Marrwan** [comment]
@SirSanctified I have been working on it, just not completed that's why. I'll push the ones I've done now.

Thank you for your ptience. I'm sorry for the delay.

**Comment by SirSanctified** [comment]
I'll wait for you then to push and open a pull request by day end. After that I'll work on it because we have to start the new milestone on Monday and we can't do so with other tasks pending.

Thanks for the feedback

**Comment by Marrwan** [comment]
@SirSanctified I haven't done a pull request yet, but I have pushed what I have done. I should complete it by the end of today
